import { AlertTriangle, FileDown, Home, LayoutDashboard, LogOut, MessageCircle, Plus, Trash2, UserPlus, Users } from "lucide-react";
import type { Camp } from "../api";

export type View = "Overview" | "Campers" | "Rooms" | "Discussion groups" | "Review" | "Exports";
const items = [["Overview",LayoutDashboard],["Campers",Users],["Rooms",Home],["Discussion groups",MessageCircle],["Review",AlertTriangle],["Exports",FileDown]] as const;

type Props={view:View;setView:(view:View)=>void;camps:Camp[];campId:string;setCampId:(id:string)=>void;deleteCamp:()=>void;newCamp:()=>void;userName:string;joinCode?:string;joinCamp:()=>void;logout:()=>void};
export function Sidebar({view,setView,camps,campId,setCampId,deleteCamp,newCamp,userName,joinCode,joinCamp,logout}:Props){return <aside className="sidebar"><div className="logo"><img src="/vault-hq-header-logo.png" alt="Vault HQ"/></div><label>Current camp<select value={campId} onChange={e=>setCampId(e.target.value)}><option value="" disabled={camps.length>0}>Select a camp</option>{camps.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{joinCode&&<div className="camp-share-code"><small>Share this camp code</small><strong>{joinCode.toUpperCase()}</strong></div>}<button className="deletecamp" onClick={deleteCamp} disabled={!campId}><Trash2 size={15}/>Delete camp</button><nav>{items.map(([name,Icon])=><button className={view===name?"on":""} onClick={()=>setView(name)} key={name}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="accountbox"><b>{userName}</b><div><button onClick={joinCamp}><UserPlus size={15}/>Join</button><button onClick={logout}><LogOut size={15}/>Sign out</button></div></div><button className="newcamp" onClick={newCamp}><Plus size={16}/>New camp</button></aside>}
export function MobileNavigation({view,setView}:Pick<Props,"view"|"setView">){return <nav className="mobile-nav" aria-label="Main navigation">{items.map(([name,Icon])=><button className={view===name?"on":""} onClick={()=>setView(name)} key={name}><Icon size={20}/><span>{name==="Discussion groups"?"Groups":name}</span></button>)}</nav>}
export function MobileCampControls({camps,campId,setCampId,deleteCamp,newCamp,userName,joinCode,joinCamp,logout}:Pick<Props,"camps"|"campId"|"setCampId"|"deleteCamp"|"newCamp"|"userName"|"joinCode"|"joinCamp"|"logout">){return <div className="mobile-controls-wrap"><div className="mobile-camp-controls"><select aria-label="Current camp" value={campId} onChange={e=>setCampId(e.target.value)}><option value="" disabled={camps.length>0}>Select a camp</option>{camps.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="secondary" onClick={newCamp} aria-label="New camp"><Plus size={18}/><span>New</span></button><button className="mobile-delete" onClick={deleteCamp} disabled={!campId} aria-label="Delete camp"><Trash2 size={18}/></button></div>{joinCode&&<div className="camp-share-code mobile-camp-code"><small>Share code for selected camp</small><strong>{joinCode.toUpperCase()}</strong></div>}<div className="mobile-account"><span><b>{userName}</b></span><button onClick={joinCamp}><UserPlus size={16}/>Join</button><button onClick={logout} aria-label="Sign out"><LogOut size={16}/><span>Sign out</span></button></div></div>}
