import { useState } from "react";
import { AlertTriangle, Check, Contact, Copy, FileDown, HandHeart, Home, LayoutDashboard, LogOut, MessageCircle, Plus, Trash2, Upload, UserPlus, Users } from "lucide-react";
import type { Camp } from "../api";

export type View = "Overview" | "Campers" | "Leaders" | "Rooms" | "Discussion groups" | "Caring" | "Review" | "Exports";
const items = [["Overview",LayoutDashboard],["Campers",Users],["Leaders",Contact],["Rooms",Home],["Discussion groups",MessageCircle],["Caring",HandHeart],["Review",AlertTriangle],["Exports",FileDown]] as const;

type Props={view:View;setView:(view:View)=>void;camps:Camp[];campId:string;setCampId:(id:string)=>void;deleteCamp:()=>void;newCamp:()=>void;userName:string;joinCode?:string;joinCamp:()=>void;logout:()=>void;importFile:()=>void;canImport:boolean};
function ShareCode({code,mobile=false}:{code:string;mobile?:boolean}){const[copied,setCopied]=useState(false);const value=code.toUpperCase();const copy=async()=>{await navigator.clipboard.writeText(value);setCopied(true);window.setTimeout(()=>setCopied(false),1800)};return <div className={`camp-share-code${mobile?" mobile-camp-code":""}`}><small>{mobile?"Share code for selected camp":"Share this camp code"}</small><span><strong>{value}</strong><button type="button" onClick={copy} aria-label={copied?"Camp code copied":"Copy camp code"}>{copied?<Check size={16}/>:<Copy size={16}/>}</button></span></div>}
export function Sidebar({view,setView,camps,campId,setCampId,deleteCamp,newCamp,userName,joinCode,joinCamp,logout}:Props){return <aside className="sidebar"><div className="logo"><img src="/vault-hq-header-logo.png" alt="Vault HQ"/></div><div className="sidebar-user"><small>Signed in as</small><b>{userName}</b></div><label>Current camp<select value={campId} onChange={e=>setCampId(e.target.value)}><option value="" disabled={camps.length>0}>Select a camp</option>{camps.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>{joinCode&&<ShareCode code={joinCode}/>}<button className="deletecamp" onClick={deleteCamp} disabled={!campId}><Trash2 size={15}/>Delete camp</button><nav>{items.map(([name,Icon])=><button className={view===name?"on":""} onClick={()=>setView(name)} key={name}><Icon size={18}/><span>{name}</span></button>)}</nav><div className="sidebar-actions"><button className="createcamp" onClick={newCamp}><Plus size={16}/>Create camp</button><button onClick={joinCamp}><UserPlus size={16}/>Join camp</button><button className="signout" onClick={logout}><LogOut size={16}/>Sign out</button></div></aside>}
export function MobileNavigation({view,setView}:Pick<Props,"view"|"setView">){return <nav className="mobile-nav" aria-label="Main navigation">{items.map(([name,Icon])=><button className={view===name?"on":""} onClick={()=>setView(name)} key={name}><Icon size={20}/><span>{name==="Discussion groups"?"Groups":name}</span></button>)}</nav>}
export function MobileCampControls({camps,campId,setCampId,deleteCamp,newCamp,joinCode,importFile,canImport}:Pick<Props,"camps"|"campId"|"setCampId"|"deleteCamp"|"newCamp"|"joinCode"|"importFile"|"canImport">){return <div className="mobile-controls-wrap"><div className="mobile-import-row"><button className="primary" onClick={importFile} disabled={!canImport}><Upload size={17}/>Import campers</button></div><div className="mobile-camp-controls"><select aria-label="Current camp" value={campId} onChange={e=>setCampId(e.target.value)}><option value="" disabled={camps.length>0}>Select a camp</option>{camps.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><button className="secondary" onClick={newCamp} aria-label="New camp"><Plus size={18}/><span>New</span></button><button className="mobile-delete" onClick={deleteCamp} disabled={!campId} aria-label="Delete camp"><Trash2 size={18}/></button></div>{joinCode&&<ShareCode code={joinCode} mobile/>}</div>}
